#!/bin/sh

imie=""
nazwisko=""
email=""
login=""
haslo=""
hobby=""

exec 3>&1

osoba=$(dialog --ok-label "OK" \
	--title "Dodawanie" \
	--form "Tworzenie nowej osoby" \ 20 50 0 \
	"Imie:" 1 1 "$imie" 1 10 40 0 \
	"Nazwisko:" 2 1 "$nazwisko" 2 10 40 0 \
	"Email:" 3 1 "$email" 3 10 40 0 \
	"Login:" 4 1 "$login" 4 10 40 0 \
	"Haslo:" 5 1 "$haslo" 5 10 40 0 \
	"Hobby:" 6 1 "$hobby" 6 10 40 0 \
	2>&1 1>&3)
exec 3>&-

plik=$(dialog --title "Wybierz sciezke" --stdout --fselect $HOME/ 10 40)

echo "$osoba" >> "$plik"