#!/bin/sh

ss=$HOME/

while :
do
exec 3>&1
sciezka=$(dialog --title "Podaj sciezke pliku/katalogu do kopiowania. CTRL+Z konczy program!" --fselect $ss 20 100 2>&1 1>&3)
cel=$(dialog --title "Podaj sciezke docelowa" --fselect $HOME/ 20 40 2>&1 1>&3)
mkdir -p $cel
cp -r $sciezka $cel
exec 3>&-
ss=$sciezka
ileplikow=`ls $sciezka | wc -l`
(
	licznik=0
	while [ $licznik -le 100 ]
	do
		echo $licznik
		licznik=$((licznik+(100/$ileplikow))) #progress bar powieksza sie w zaleznosci od ilosci plikow
		sleep 0.1
	done
) | dialog --title "gauge" --gauge "Trwa kopiowanie.." 10 40 0
done